import Head from 'next/head';
import Image from 'next/image';

import axios from 'axios';
import styles from '../styles/Home.module.css';

export default function Index(props) {
  const todoList = props.data;
  return (
    <div className={styles.container}>
      <Head>
        <title>useSWR library demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {todoList.map((todo, index) => (
            <li key={index}>
              <a>{todo.task}</a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await axios.get('http://localhost:3000/api/todos');
  return {
    props: { data: res.data.todos },
  };
};
